artifacts_root : artifacts_root

data_ingestion:
  root_dir: artifects/data_ingestion
  source_URL: https://github.com/rajkumar1447/End-to-End-Machine-Learning-Project/blob/main/winequality-data.zip
  local_data_file: artifects/data_ingestion/data.zip
  unzip_dir: artifects/data_ingestion